//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsRovers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarsRovers.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty data, please insert an information!.
        /// </summary>
        public static string EmptyData {
            get {
                return ResourceManager.GetString("EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover is outside of the plateau!.
        /// </summary>
        public static string OutsidePlateau {
            get {
                return ResourceManager.GetString("OutsidePlateau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Parameters is wrong insert limit information with space &quot;X Y&quot;!.
        /// </summary>
        public static string PlateauWrong {
            get {
                return ResourceManager.GetString("PlateauWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate should be bigger than 0!.
        /// </summary>
        public static string PlateauXWrong {
            get {
                return ResourceManager.GetString("PlateauXWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate should be bigger than 0!.
        /// </summary>
        public static string PlateauYWrong {
            get {
                return ResourceManager.GetString("PlateauYWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Parameters is wrong insert rover rommands with only using &quot;L R M&quot; without space!.
        /// </summary>
        public static string RoverCommandsWrong {
            get {
                return ResourceManager.GetString("RoverCommandsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction should be N, S, W, E!.
        /// </summary>
        public static string RoverDirectionWrong {
            get {
                return ResourceManager.GetString("RoverDirectionWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given Parameters is wrong insert rover position with space &quot;X Y D&quot;!.
        /// </summary>
        public static string RoverPositionWrong {
            get {
                return ResourceManager.GetString("RoverPositionWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate should not be bigger than plateau. Max plateau X is {0}!.
        /// </summary>
        public static string RoverPositionXWrong {
            get {
                return ResourceManager.GetString("RoverPositionXWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate should be bigger than 0!.
        /// </summary>
        public static string RoverPositionXWrong2 {
            get {
                return ResourceManager.GetString("RoverPositionXWrong2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate should not be bigger than plateau. Max plateau Y is {0}!.
        /// </summary>
        public static string RoverPositionYWrong {
            get {
                return ResourceManager.GetString("RoverPositionYWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate should be bigger than 0!.
        /// </summary>
        public static string RoverPositionYWrong2 {
            get {
                return ResourceManager.GetString("RoverPositionYWrong2", resourceCulture);
            }
        }
    }
}
